#!/usr/bin/env python3
"""LDPlayer / 模拟器端到端冒烟：ADB 截图 → 取色/模板 → 打包 → 安装 → 无障碍 → 自动跑脚本。"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import cv2
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from packager.packager_cli import build, validate_project  # noqa: E402
from studio.services.adb_service import AdbService  # noqa: E402
from studio.services import vision_pc  # noqa: E402

PROJECT = ROOT / "examples" / "ldplayer-test"
DIST = ROOT / "dist"
TEMPLATE_SIZE = 80
LOG_DONE = "done:main"


def _center_crop(bgr: np.ndarray, cx: int, cy: int, size: int) -> tuple[np.ndarray, tuple[int, int, int, int]]:
    h, w = bgr.shape[:2]
    half = size // 2
    x1 = max(0, cx - half)
    y1 = max(0, cy - half)
    x2 = min(w, x1 + size)
    y2 = min(h, y1 + size)
    if x2 - x1 < size:
        x1 = max(0, x2 - size)
    if y2 - y1 < size:
        y1 = max(0, y2 - size)
    crop = bgr[y1 : y1 + size, x1 : x1 + size].copy()
    return crop, (x1, y1, size, size)


def write_main_lua(
    project_dir: Path,
    *,
    bgr: tuple[int, int, int],
    template_rel: str,
    tap_x: int,
    tap_y: int,
) -> None:
    b, g, r = bgr
    text = f'''-- Auto-generated by tools/run_emulator_test.py
bot.log("ldplayer-test 开始")
bot.delay(1)
bot.findColor({b}, {g}, {r}, {{ tol = 18, timeout = 8 }})
local x, y = bot.findImage("{template_rel}", {{ threshold = 0.85, timeout = 10 }})
if x then
  bot.log(string.format("模板命中 (%d,%d)", x, y))
  bot.tap(x, y)
else
  bot.tap({tap_x}, {tap_y})
end
bot.log("ldplayer-test 完成")
'''
    (project_dir / "main.lua").write_text(text, encoding="utf-8")


def ensure_test_runtime(project_dir: Path, *, sdk: int) -> None:
    cfg_path = project_dir / "project.json"
    cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
    cfg["entry"] = "main.lua"
    cfg["script_language"] = "lua"
    runtime = cfg.setdefault("runtime", {})
    runtime["auto_run"] = True
    if sdk >= 30:
        runtime["screenshot_mode"] = "accessibility"
    else:
        runtime["screenshot_mode"] = "media_projection"
    cfg_path.write_text(json.dumps(cfg, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    adb = AdbService()
    serial = adb.default_serial()
    if not serial:
        print("FAIL: 未检测到 ADB 设备")
        return 1
    print(f"ADB 设备: {serial}")

    png = adb.capture_png(serial)
    screen = vision_pc.decode_png(png)
    h, w = screen.shape[:2]
    cx, cy = w // 2, h // 2
    b, g, r = [int(v) for v in screen[cy, cx]]
    bgr = (b, g, r)
    print(f"屏幕: {w}x{h}  中心色 BGR={bgr}")

    crop, roi = _center_crop(screen, cx, cy, TEMPLATE_SIZE)
    img_dir = PROJECT / "image"
    img_dir.mkdir(parents=True, exist_ok=True)
    tpl_name = "center_tpl.png"
    tpl_path = img_dir / tpl_name
    cv2.imwrite(str(tpl_path), crop)
    print(f"模板: {tpl_path}  ROI={roi}")

    write_main_lua(
        PROJECT,
        bgr=bgr,
        template_rel=f"image/{tpl_name}",
        tap_x=cx,
        tap_y=cy,
    )
    ensure_test_runtime(PROJECT, sdk=adb.get_sdk_version(serial))
    mode = "accessibility" if adb.get_sdk_version(serial) >= 30 else "media_projection"
    print(f"已写入: {PROJECT / 'main.lua'}（Lua + auto_run + {mode} 截图）")

    cfg = validate_project(PROJECT)
    package_id = cfg["package_id"]
    apk_out = DIST / "ldplayer-test.apk"
    print("打包 APK …")
    build(PROJECT, apk_out, release=False)
    print(f"APK: {apk_out} ({apk_out.stat().st_size // 1024} KB)")

    print("安装 APK …")
    adb.install_apk(str(apk_out), serial)

    print("开启无障碍服务 …")
    a11y_ok = adb.enable_accessibility(package_id, serial=serial)
    if not a11y_ok:
        print("提示: ADB 未能写入无障碍设置，请在模拟器内手动开启 LDPlayer Test 无障碍")
    time.sleep(2.0)
    adb._run(["shell", "am", "force-stop", package_id], serial=serial, check=False, timeout=15)

    adb._run(["logcat", "-c"], serial=serial, check=False, timeout=10)
    print("启动应用（auto_run 将自动执行脚本）…")
    adb.start_package(package_id, serial)

    if adb.get_sdk_version(serial) < 30:
        print("API<30：尝试自动点击录屏授权 …")
        time.sleep(2.5)
        adb.tap_projection_allow(serial)

    script_ok = adb.wait_script_status(package_id, LOG_DONE, serial=serial, timeout_sec=90.0)
    if not script_ok:
        script_ok = adb.wait_logcat("flow=main 完成", serial=serial, timeout_sec=15.0)
    status_text = adb.read_script_status(package_id, serial)
    tpl = cv2.imread(str(tpl_path))
    match = vision_pc.match_template(screen, tpl, threshold=0.8) if tpl is not None else None
    color_hit = vision_pc.find_color(screen, bgr, tol=20)

    print("\n=== 测试结果 ===")
    print(f"serial:     {serial}")
    print(f"screen:     {w}x{h}")
    print(f"center_bgr: {bgr}")
    print(f"template:   image/{tpl_name}")
    print(f"apk:        {apk_out}")
    print(f"package:    {package_id}")
    print(f"color_hit:  {color_hit}")
    print(f"tpl_match:  {match.score:.3f} @ ({match.center_x},{match.center_y})" if match else "tpl_match:  None")
    print(f"install:    OK")
    print(f"start:      OK")
    print(f"script_run: {'OK' if script_ok else 'TIMEOUT（请手动开启无障碍 + 录屏）'}")
    if status_text:
        print(f"status_file: {status_text}")
    return 0 if script_ok else 2


if __name__ == "__main__":
    raise SystemExit(main())
